config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/about", to: "pages#about"
  resources :posts do
    resources :comments, only: [:create, :update, :destroy, :edit]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  after_create_commit -> { broadcast_append_to "comments" }
  after_update_commit -> { broadcast_replace_to "comments" }
  after_destroy_commit -> { broadcast_remove_to "comments" }
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  has_many :comments, dependent: :destroy

  # after_create_commit -> { broadcast_prepend_later_to "posts" }
  # after_update_commit -> { broadcast_replace_later_to "posts" }
  # after_destroy_commit -> { broadcast_remove_to "posts" }

  broadcasts_to ->(post) { "posts" }, inserts_by: :prepend
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action -> { sleep 3 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create, :destroy, :update, :edit]

  def create
    @comment = @post.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.turbo_stream
        format.html { redirect_to posts_path }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(:new_comment, partial: "comments/form", locals: { comment: @comment }) }
        format.html { render :new }
      end
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    respond_to do |format|
      if @comment.destroy
        format.turbo_stream { render turbo_stream: turbo_stream.remove(@comment) }
        format.html { redirect_to posts_path }
      else
        format.html { redirect_to @post, notice: "Comment could not be deleted." }
      end
    end
  end

  def update
    @comment = @post.comments.find(params[:id])

    respond_to do |format|
      if @comment.update(comment_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@comment, partial: "comments/comment", locals: { comment: @comment }) }
        format.html { redirect_to @post, notice: "Comment was successfully updated." }
      else
        format.html { redirect_to @post, notice: "Comment could not be updated." }
      end
    end
  end

  def edit
    @comment = @post.comments.find(params[:id])
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to posts_path }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def turbo_frame_requested?
    request.headers['Turbo-Frame'].present?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>" class="animate__animated" data-animate-in="animate__bounceIn" data-animate-out="animate__bounceOut">
  <%= comment.body %>
  <%= turbo_frame_tag :edit_comment do %>
    <%= link_to "Edit", edit_post_comment_path(comment.post, comment) %>
  <% end %>
  <%= link_to "Delete", [comment.post, comment], data: { turbo_method: :delete } %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ comment.post, comment ], data: { controller: 'reset-form', action: "turbo:submit-end->reset-form#reset"} do |form| %>
  <%= form.text_area :body %><br />
  <%= form.submit %>
  <%= link_to "Close Comment", '#' if turbo_frame_requested? %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append :comments, partial: 'comments/comment', locals: { comment: @comment } %>

<%#= turbo_stream.update :new_comment, partial: 'comments/form', locals: { post: @post, comment: @post.comments.new } %>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h2>Edit comment</h2>

<%= turbo_frame_tag :edit_comment do %>
  <%= render 'form', comment: @comment %>
<% end %>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog7-Turbo-Broadcast</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'rorlab_logo_circle_100px.png' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

<%= turbo_frame_tag 'nav' do %>
  <%= link_to 'Root', '/' %>
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= turbo_frame_tag 'nav' do %>
  <%= link_to 'About', '/about' %>
<% end %>

<%= link_to "Posts", posts_path %>

app/views/posts/_form.html.erb
  <%= form_with model: post, data: { controller: 'reset-form', action: 'turbo:submit-end->reset-form#reset'} do |form| %>
    <%#= render 'posts/post_errors' %>

    <div>
      <%= form.text_field :title, placeholder: 'title', autofocus: true %>
      <% post.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    <div>
      <%= form.text_area :body, placeholder: 'body' %>
    </div>
    <div>
      <%= form.submit %>
      <%= link_to 'Close Form', posts_path if turbo_frame_requested? %>
    </div>
  <% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="animate__animated" data-animate-in="animate__bounceIn" data-animate-out="animate__bounceOut">
    <%= post.id %>.
    <%= link_to post.title, post %>
  <%= turbo_frame_tag dom_id(post, :edit) do %>
    <%= link_to "Edit", edit_post_path(post) %>
  <% end %>
    <%= link_to "Delete", post, data: { turbo_method: :delete } %>
</div>

app/views/posts/_post_errors.html.erb
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= turbo_frame_tag dom_id(@post, :edit) do %>
  <%= render 'posts/form', post: @post %>
<% end %>

<%= link_to "Go to posts", posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<p>
  <%= link_to "New post", new_post_path, data: { turbo_frame: dom_id(Post.new) } %>
</p>

<%= turbo_frame_tag Post.new do %>
<% end %>

<%= turbo_stream_from :posts %>

<div id="posts">
  <%= render @posts %>
</div>

<%= link_to "Root", root_path %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= turbo_frame_tag @post do %>
  <%= render 'posts/form', post: @post %>
<% end %>

<%= link_to "Go to posts", posts_path %>

app/views/posts/show.html.erb
<div>
  <p>Title:</p>
  <%= @post.title %>
</div>

<div>
  <p>Body:</p>
  <%= @post.body %>
</div>

<div>
  <%= @post.created_at %>
</div>

<div>
  <%= @post.updated_at %>
</div>

<h3>Comments</h3>

<%= turbo_stream_from :comments %>
<div id="comments">
  <%= render @post.comments.order(created_at: :asc) %>
</div>

<div id="new_comment">
  <%= render 'comments/form', comment: @post.comments.new %>
</div>

<ul>
  <li><%= link_to "Go to Posts", posts_path %></li>
</ul>